import React from 'react'

export default function About() {
  return (
    <div>
      <h1>hello!</h1>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maxime fugit vel consequuntur itaque quis inventore sint odit. Vero animi aliquid harum eaque dolores nisi blanditiis, quam quas assumenda! Odit molestiae perferendis ea aliquid a similique repellendus cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta soluta cupiditate quo impedit assumenda doloremque explicabo itaque repellendus ipsum libero repudiandae facere fugit pariatur illum, odit beatae fuga, nulla qui dolorem culpa optio error cumque. Dignissimos illum consequuntur, asperiores ducimus expedita quidem quisquam repudiandae sequi voluptas distinctio numquam nostrum rem corrupti aspernatur dolore pariatur, ex natus iste eos quasi. Distinctio doloremque dignissimos magnam cumque esse sequi incidunt. Voluptatibus quam commodi sunt illo repellat excepturi quis, assumenda, ipsam dolore nihil non alias possimus quibusdam recusandae iure cumque adipisci dicta velit veniam. Rerum ipsa aspernatur harum minus ea esse, molestias tempora mollitia. Lorem ipsum dolor sit amet consectetur adipisicing elit. Est veritatis eos, quis natus necessitatibus consectetur inventore officiis nobis blanditiis numquam dolor neque consequatur accusamus. Incidunt beatae dolor ut temporibus earum doloremque placeat veniam numquam vero soluta maxime saepe accusantium amet ipsa cupiditate assumenda cum ea atque quod nisi ipsam, rerum exercitationem sed! Mollitia quia pariatur dolor deleniti obcaecati temporibus, nam facilis rerum sint, harum debitis labore quas enim asperiores assumenda incidunt illum, magni voluptate? Nam magnam in eveniet consequuntur assumenda cumque esse! Ea repellat aperiam officia, aspernatur eum assumenda nulla exercitationem dolor suscipit saepe labore laborum aliquam, adipisci nemo omnis, fugiat voluptatibus! Voluptatibus asperiores aspernatur tempora aliquam alias odio officiis optio, eaque quo nemo delectus ipsam assumenda dolorem beatae magnam illo. Iure ex necessitatibus ad, vitae laboriosam laborum dolor rerum. Nobis eveniet dolor quasi delectus exercitationem esse repudiandae commodi mollitia impedit dolorem sapiente molestiae, aperiam ea. Dolore sint maiores recusandae, in cum odio cumque nihil praesentium neque architecto tempore magnam sapiente nesciunt excepturi quas, eveniet, nobis ex iste fugit. Impedit molestias illum aut repellat unde, facere temporibus recusandae, similique commodi eos fuga nam officiis deleniti quis dolore magni, at incidunt optio! Consequatur blanditiis veritatis magni pariatur qui alias, aut nemo!
      </p>
    </div>
  )
}
